### ISSUE TITLE
Support specifying redirect URI

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/init#1]
The current [app creation task](https://github.com/PlaceOS/init/blob/6eb47aae60c9b9de4d0329b2a2e385b4d0a2ce48/src/tasks/entities.cr#L78-L130) assumes a static redirect URI based on the base path. While this may be a sensible default, it is not always the case. Providing an additional arg to optionally specify `redirect_uri` would be useful.

**Comment by caspiano** [comment]
hey @KimBurgess, want me to jump on this and close this out?

**Comment by KimBurgess** [comment]
Yes please - had forgotten about this tbh!
