### ISSUE TITLE
Sam task arguments being lost

### ISSUE THREAD

**Issue by viv-4** [PlaceOS/init#11]
When running a sam task the arguments are being lost

If you run
```
docker-compose run init make sam create:authority domain="test.com"
```
It will instead use the `PLACE_DOMAIN` env var

Possibly happening here: https://github.com/PlaceOS/init/blob/d54553a3007388da3be4ccee97a3146d84426cb3/Makefile#L7

**Comment by caspiano** [comment]
As a temporary workaround, set the environment variables defined for the task in the README.

i.e.
`docker-compose run init make sam create:authority domain="test.com"`
becomes
`docker-compose run --no-deps -e PLACE_DOMAIN=test.com init make sam create:authority`
