### ISSUE TITLE
S3 restore using init

### ISSUE THREAD

**Issue by OllieMoylette** [PlaceOS/init#19]
Haven't been able to successfully restore S3 backup for RethinkDB locally or using Fargate. Backup using same AWS credentials and placeos/rethinkdb-backup works successfully. Restore using local copy of backup works successfully also. 

Testing method as follows...

1. Bring up the init container to stay up...
docker run -it --name rethinkdb-restore --network=placeos -v /home/placeos/docker/restore/rethinkdb_dump_1610433479.tar.gz:/rethinkdb_backup.tar.gz placeos/init /bin/bash

2. Execute a restore from a local file from inside container (works fine)...
bash-5.0# rethinkdb restore rethinkdb_backup.tar.gz -c {IP of rethink container}:28015 --force
Extracting archive file...  Done (0 seconds)
Importing from directory...
  [========================================] 100%
  29 rows imported to 24 tables in 3.52 secs

3. Test S3 restore inside container...
bash-5.0# /scripts/task restore:rethinkdb rethinkdb_host={IP of rethinkdb container} rethinkdb_port=28015 force_restore=true aws_region=us-east-1 aws_s3_bucket={S3 bucket name} aws_s3_object={S3 object name} aws_key={AWS KEY} aws_secret={AWS SECRET} aws_kms_key_id={AWS KMS KEY ID}

level=INFO time=2021-01-12T23:11:25Z source=place_os.tasks.restore rethinkdb_host=localhost rethinkdb_port=28015 force_restore=true aws_s3_object={S3 object name} aws_s3_bucket={S3 bucket name} aws_region=us-east-1 message=pulling backup from S3

usr/share/crystal/src/gc/boehm.cr:110:5 in 'from_response'
scripts/lib/awscr-s3/src/awscr-s3/http.cr:93:9 in 'handle_response!'
scripts/lib/awscr-s3/src/awscr-s3/http.cr:83:9 in 'rethinkdb_restore:rethinkdb_host:rethinkdb_port:rethinkdb_password:force_restore:aws_region:aws_key:aws_secret:aws_s3_bucket:aws_s3_object:aws_kms_key_id'
scripts/src/sam.cr:41:5 in '->'
scripts/lib/sam/src/sam/execution.cr:20:7 in '__crystal_main'
usr/share/crystal/src/crystal/main.cr:105:5 in 'main'
src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
Document is empty

4. We can see from above - although I specify the ip address of the RethinkDB container in the parameters. - it gets listed as localhost in the INFO message and we get a "Document is empty message". I haven't been able to detect a copy of the S3 backup file inside the container either.

**Comment by caspiano** [comment]
Closed by #21
