### ISSUE TITLE
Update default entities

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/init#31]
The default entities currently created when running within a non-production environment are targeted towards testing, rather than initial usage scenarios for development. This results in unnecessary manual config steps for the majority of users.

This is partially resolved via #24, but would good to revisit all entity creation and ensure is relevant for current use cases.

**Comment by caspiano** [comment]
Even #24 is for testing

**Comment by caspiano** [comment]
Currently, no entities are generated beyond the authority, application, backoffice repository, and user _if_ the environment is not in production.
